# Schools of Urban Informatics 

```{r, include=FALSE}
source("common.R")
```



- Sociological origins
- the chicago school
  - Park and Burgess
  - the key findings from _The City_
  - Discuss _how_ these findings were generated
    - inductive approaches to theory, ONLY
- the sante fe school
  - this is the complete other end of the example
  - sante fe is a group of physical scientists looking to use hyper-modern techniques and apply theory to observed social data
  - this group has a general set of theories that they use to evaluate urban life
- where does the Boston School fit in?
  - let's step back to understand the two general approaches to scientific inquiry
    1. Inductive - finding something from the data (think chicago)
    2. Deductive - having a theory and setting out to explicitly test that (think psychology experiment)
  - Overview of inductive
  - Overview of deductive
  - the Boston School is a hybrid approach
  - Next Chapter: Let us use the example of broken windows theory and the development of ecometrics
  
some questions to ponder:

- what is a strnegth of the chicago school?
- what is the strength of the santa fe institute?
  - https://www.santafe.edu/research/projects/cities-scaling-sustainability
- what do you think is the ideal approach? is it one or the other? a blend? something entirely new?

