<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 26 Spatial Analysis | Urban Informatics Toolkit</title>
<meta name="author" content="Josiah Parry">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.5.3/header-attrs.js"></script><script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.3.9000/tabs.js"></script><script src="libs/bs3compat-0.2.3.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Urban Informatics Toolkit</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Welcome</a></li>
<li class="book-part">Foundations of Urban Informatics</li>
<li><a class="" href="the-utility-and-danger-of-big-data.html"><span class="header-section-number">2</span> The Utility and Danger of Big Data</a></li>
<li><a class="" href="data-in-the-municipal-context.html"><span class="header-section-number">3</span> Data in the municipal context</a></li>
<li><a class="" href="approaches-to-and-schools-of-urban-informatics.html"><span class="header-section-number">4</span> Approaches to and Schools of Urban Informatics</a></li>
<li><a class="" href="ecometrics.html"><span class="header-section-number">5</span> Ecometrics</a></li>
<li class="book-part">Toolkit Foundations</li>
<li><a class="" href="the-basics.html"><span class="header-section-number">6</span> The basics</a></li>
<li><a class="" href="r-as-a-calculator.html"><span class="header-section-number">7</span> R as a calculator</a></li>
<li><a class="" href="reading-data.html"><span class="header-section-number">8</span> Reading data</a></li>
<li><a class="" href="exploratory-visual-analysis.html"><span class="header-section-number">9</span> Exploratory Visual Analysis</a></li>
<li><a class="" href="general-data-manipulation.html"><span class="header-section-number">10</span> General data manipulation</a></li>
<li><a class="" href="thats-too-much-data.html"><span class="header-section-number">11</span> That’s too much data</a></li>
<li><a class="" href="the-pipe.html"><span class="header-section-number">12</span> The pipe %&gt;%</a></li>
<li><a class="" href="creating-new-measures.html"><span class="header-section-number">13</span> Creating new measures</a></li>
<li><a class="" href="data-structures.html"><span class="header-section-number">14</span> Data Structures</a></li>
<li><a class="" href="summary-statistics.html"><span class="header-section-number">15</span> Summary statistics</a></li>
<li><a class="" href="summarizing-the-tidy-way.html"><span class="header-section-number">16</span> Summarizing the tidy way</a></li>
<li><a class="" href="toolkit-review.html"><span class="header-section-number">17</span> Toolkit review</a></li>
<li class="book-part">Vizualization Strategies</li>
<li><a class="" href="layered-i.html"><span class="header-section-number">18</span> Grammar of layered graphics I</a></li>
<li><a class="" href="visualizing-trends-and-relationships.html"><span class="header-section-number">19</span> Visualizing Trends and Relationships</a></li>
<li><a class="" href="grammer-of-layered-graphics-ii.html"><span class="header-section-number">20</span> Grammer of layered graphics II</a></li>
<li><a class="" href="visualizing-beyond-2-dimensions.html"><span class="header-section-number">21</span> Visualizing beyond 2-dimensions</a></li>
<li><a class="" href="visualizing-through-time.html"><span class="header-section-number">22</span> Visualizing through time</a></li>
<li><a class="" href="visualization-review.html"><span class="header-section-number">23</span> Visualization Review</a></li>
<li class="book-part">Expanding the Toolkit</li>
<li><a class="" href="multiple-data-sets.html"><span class="header-section-number">24</span> Multiple data sets</a></li>
<li><a class="" href="statistics.html"><span class="header-section-number">25</span> Statistics</a></li>
<li><a class="active" href="spatial-analysis.html"><span class="header-section-number">26</span> Spatial Analysis</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="spatial-analysis" class="section level1" number="26">
<h1>
<span class="header-section-number">26</span> Spatial Analysis<a class="anchor" aria-label="anchor" href="#spatial-analysis"><i class="fas fa-link"></i></a>
</h1>
<p>In the very beginning of the book we discussed some of the benefits of administrative data. One of the benefits mentioned is that administrative data are inherently <strong>spatial</strong>. Most data tend to be spatial in nature. This is because most events happen at a physical place. In the context of administrative data, we know that all data recorded at that level must fall within the municipal boundaries. Often we know the location within the municipality to a much finer scale—i.e. the block group, the voting ward, or even the exact point location.</p>
<p>Identifying whether or not your data is spatial is easiest when there are geographic components present such as latitude and longitude. However, your data can also be spatial even if it isn’t explicitly stated. Some things you can keep an eye out for are things like neighborhood, towns, county, etc. as these are location specific. It is likely that you will be performing analyses rooted in space and accounting for things such as counties but perhaps without using any geospatial techniques.</p>
<p>In this section we will go over the very basics of geospatial analysis.</p>
<div id="types-of-spatial-data" class="section level2" number="26.1">
<h2>
<span class="header-section-number">26.1</span> Types of spatial data<a class="anchor" aria-label="anchor" href="#types-of-spatial-data"><i class="fas fa-link"></i></a>
</h2>
<p>Within the field of Geographic Information Systems (<strong>GIS</strong>) there are two general umbrellas in which data fall under. These are vector and raster data.</p>
<p><strong>Vector</strong> data is what you will find yourself working with most frequently. Most simply put they are <em>“points, lines, and polygons.”</em> The basis of vector data is the coordinate point. Just like the scatter plots we have built, each coordinate point is a combination of an x and y value (longitude and latitude respectively). This combination of x and y will tell us where something is. By combining two or more points we can trace along a path—think of the connect the dots diagrams you would do at restaurants as a kid—and create line segments. If, however, at any point these lines close, you now have a polygon.</p>
<p>The other umbrella of data is known as <strong>raster</strong> data. Raster data are to deal with more complex data that cannot easily be captured by a single point. Rasters are used to “represent spatially continuous phenomenon.”<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;R Spatial. &lt;a href="https://rspatial.org/raster/spatial/Spatialdata.pdf" class="uri"&gt;https://rspatial.org/raster/spatial/Spatialdata.pdf&lt;/a&gt;.&lt;/p&gt;'><sup>77</sup></a> Raster analysis is done to evaluate things like changing vegetation, elevation and slope modeling, analysing reflective surfaces, among much more. Raster analysis typically relies on satellite imagery or LiDAR laser point cloud data. Raster analysis is an extremely complex topic and requires devoted attention. As such, we will not cover it in this book. But, know that it exists and is out there!</p>
<div class="inline-figure"><img src="static/2019-points-lines-polygons.png" width="100%"></div>
</div>
<div id="working-with-spatial-data" class="section level2" number="26.2">
<h2>
<span class="header-section-number">26.2</span> Working with spatial data<a class="anchor" aria-label="anchor" href="#working-with-spatial-data"><i class="fas fa-link"></i></a>
</h2>
<p>Working with spatial data is made rather straightforward by the <a href="https://github.com/r-spatial/sf"><code>sf</code></a> package.</p>
<p>sf is shorthand for <em>simple features</em>. sf let’s us represent physical objects or phenomena in that occur the real world through data. It is built upon an international standard that “describes how such objects can be stored in and retrieved from databases, and which geometrical operations should be defined for them.” (sf vinette, 1).</p>
<p>All simple features are representation of vector data. That is that they are composed of points. These points are usually represented two-dimensionally with longitude and latitude (x and y). We can associate a third dimension, usually altitude, if so desired to extend to three dimensions: longitude, latitude, and altitude (x, y, &amp; z). In our cases, however, this will not be used.</p>
<p>In this section we will working with the <code>locations</code> Airbnb dataset. <code>locations</code> contains the longitude and latitude of Airbnb listings in Boston. These are an example of point data (which contain two-dimension).</p>
</div>
<div id="creating-simple-features-from-a-tibble" class="section level2" number="26.3">
<h2>
<span class="header-section-number">26.3</span> Creating simple features from a tibble<a class="anchor" aria-label="anchor" href="#creating-simple-features-from-a-tibble"><i class="fas fa-link"></i></a>
</h2>
<p>Begin by installing the <code>sf</code> (simple-features) package and loading the <code>locations</code> Airbnb dataset.</p>
<div class="sourceCode" id="cb328"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># install.packages("sf")</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="va">locations</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/airbnb/locations.csv"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">locations</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##      id longitude latitude
##   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1  3781     -71.0     42.4
## 2  5506     -71.1     42.3
## 3  6695     -71.1     42.3
## 4  8789     -71.1     42.4
## 5 10730     -71.1     42.4
## 6 10813     -71.1     42.3</code></pre>
<p>So far everything is the same. We have read in our dataset and created a tibble. The next step is to make this tibble a simple feature. Fortunately, sf keeps this process rather simple for us by representing spatial data in native R data formats—namely, the data frame. To make simple features from an existing tibble, we need to cast the object as an <code>sf</code> object. And we do this with <code><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf()</a></code>.</p>
<p>Generally when we cast objects we use functions like <code><a href="https://rdrr.io/r/base/integer.html">as.integer()</a></code> or <code><a href="https://rdrr.io/pkg/tibble/man/as_tibble.html">as_tibble()</a></code>. Here, there is a prefixed <code>st_</code>. This stands for <em>spatial transformation</em>. All transformations are prefixed as such—this is in an effort to keep continuity between GIS tools. Most functions cast objects to other classes with no function arguments. <code><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf()</a></code> unfortunately cannot read your mind and is not aware of what the geometry is in the tibble. As such, we need to use the <code>coords</code> argument in <code><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf()</a></code>. <code>coords</code> gives us the ability to tell sf what the columns are that contain our coordinate points. For point data we need to provide a character vector of length two with the x and y dimensions aka longitude and latitude.</p>
<blockquote>
<p>Note that we are likely used to saying <em>lat, long</em>, but that actually maps to <em>y, x</em>. This is something that trips everyone up! Just make sure you put longitude in the x spot and latitude in the y spot.</p>
</blockquote>
<p>To convert the <code>locations</code> data frame to a simple feature we will use <code><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf()</a></code> and set the <code>coords</code> argument to <code><a href="https://rdrr.io/r/base/c.html">c("longitude", "latitude")</a></code>.</p>
<div class="sourceCode" id="cb330"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">locations</span>,
         coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"longitude"</span>, <span class="st">"latitude"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Simple feature collection with 3799 features and 1 field
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -71.1728 ymin: 42.23576 xmax: -70.99595 ymax: 42.39549
## CRS:            NA
## # A tibble: 3,799 x 2
##       id             geometry
##    &lt;dbl&gt;              &lt;POINT&gt;
##  1  3781 (-71.02991 42.36413)
##  2  5506 (-71.09559 42.32981)
##  3  6695 (-71.09351 42.32994)
##  4  8789 (-71.06265 42.35919)
##  5 10730  (-71.06185 42.3584)
##  6 10813 (-71.08904 42.34961)
##  7 10986 (-71.05075 42.36352)
##  8 16384  (-71.07132 42.3581)
##  9 18711 (-71.06096 42.32212)
## 10 22195  (-71.0793 42.34558)
## # … with 3,789 more rows</code></pre>
<p>Now that we have successfully created a simple feature we can see that we no longer have the columns <code>longitude</code> and <code>latitude</code> but a <code>geometry</code> column instead. Notice that when printed, the object tells us what type of geometry we are working with, it’s dimensions, and the bounding box for these points.</p>
<blockquote>
<p>A bounding box is the furthest extent that our data reaches in both latiude and longitude.</p>
</blockquote>
<p>The printed object informs us that there are actually two missing pieces of information the epsg and proj4string. This is because we failed to specify a <strong>coordinate reference system</strong> (CRS). While this book is not intended as an introduction to GIS, this is still worth briefly expanding upon. We use a CRS because we are trying to place points in two-dimensions when the Earth is round! Try peeling and orange and laying the peel flat. It’s impossible. There is now way to visualize a circle as a rectangle without introducing <em>some</em> error. This is what a CRS accounts for. There are many CRS for each type of map projection and each type of unit. Most, if not all, of the frustration you may encounter when working with spatial data will be due to mismatching CRS.</p>
<p>Fortunately we will <em>most likely</em> be working with data that is collected using the <strong>WGS84</strong> reference system. This is a CRS that is used to define a global reference system that is used consistently throughout government agencies, and typically in online data recording. The Airbnb data uses this references system.</p>
<p>Most other online data sources use this reference system as well. For example Google and Twitter provide their data using this CRS. The times when you are most likely to encounter a CRS isn’t WGS84 is when working with data from local agencies that need highly accurate and tailored spatial data. This would be agencies like water departments, and forestry groups, etc.</p>
<p>To ensure that our data are properly represented in space, we need to provide the CRS in the creation of our simple features. We do this by specifying the <code>crs</code> argument. <code>crs</code> will accept a number that indicates what projection you are using. There are too many CRS identifiers to commit to memory. This information is usually recorded in the original data source. Be sure to confirm the spatial dimensions! For WGS84, the CRS identifier is <code>4326</code>. This is probably worth committing to memory.</p>
<p><a href="https://confluence.qps.nl/qinsy/latest/en/world-geodetic-system-1984-wgs84-182618391.html#id-.WorldGeodeticSystem1984(WGS84)v9.1-WGS84definitions" class="uri">https://confluence.qps.nl/qinsy/latest/en/world-geodetic-system-1984-wgs84-182618391.html#id-.WorldGeodeticSystem1984(WGS84)v9.1-WGS84definitions</a></p>
<p>We will now create an object called <code>loc_sf</code> using <code><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf()</a></code> and providing both the <code>coords</code> and the <code>crs</code>.</p>
<div class="sourceCode" id="cb332"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">loc_sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">locations</span>,
         coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"longitude"</span>, <span class="st">"latitude"</span><span class="op">)</span>,
         crs <span class="op">=</span> <span class="fl">4326</span><span class="op">)</span>

<span class="va">loc_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 3799 features and 1 field
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -71.1728 ymin: 42.23576 xmax: -70.99595 ymax: 42.39549
## CRS:            EPSG:4326
## # A tibble: 3,799 x 2
##       id             geometry
##  * &lt;dbl&gt;          &lt;POINT [°]&gt;
##  1  3781 (-71.02991 42.36413)
##  2  5506 (-71.09559 42.32981)
##  3  6695 (-71.09351 42.32994)
##  4  8789 (-71.06265 42.35919)
##  5 10730  (-71.06185 42.3584)
##  6 10813 (-71.08904 42.34961)
##  7 10986 (-71.05075 42.36352)
##  8 16384  (-71.07132 42.3581)
##  9 18711 (-71.06096 42.32212)
## 10 22195  (-71.0793 42.34558)
## # … with 3,789 more rows</code></pre>
<p>Since an sf object is also a data frame we are able to perform all of the operations that we may with a normal tibble such as selecting columns, joining, mutating etc.</p>
<div class="sourceCode" id="cb334"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="va">loc_sf</span><span class="op">)</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 1 field
## geometry type:  MULTIPOINT
## dimension:      XY
## bbox:           xmin: -71.1728 ymin: 42.23576 xmax: -70.99595 ymax: 42.39549
## CRS:            EPSG:4326
## # A tibble: 1 x 2
##       n                                                                 geometry
## * &lt;int&gt;                                                         &lt;MULTIPOINT [°]&gt;
## 1  3799 ((-71.1728 42.34835), (-71.17174 42.34854), (-71.17173 42.34923), (-71.…</code></pre>
<p>Notice that it keeps the geometry even when counting. When our data is spatial, we have to incorporate the geometry into our computations. This often times leads to slower processing times. So if you do not immediately need the geometry, my recommendation is that you join it back on as late as possible. You can cast an sf object to a tibble with <code><a href="https://rdrr.io/pkg/tibble/man/as_tibble.html">as_tibble()</a></code></p>
<div class="sourceCode" id="cb336"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tibble/man/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">loc_sf</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1  3799</code></pre>
<p>Notice that we now lose the geometry column. This is because we have stopped keeping track of the geometry.</p>
</div>
<div id="plotting-sf-objects-with-ggplot" class="section level2" number="26.4">
<h2>
<span class="header-section-number">26.4</span> Plotting sf objects with ggplot<a class="anchor" aria-label="anchor" href="#plotting-sf-objects-with-ggplot"><i class="fas fa-link"></i></a>
</h2>
<p>Plotting sf objects is made rather straightforward with ggplot2. Since sf objects contain a ton of spatial information this is inferred from ggplot. As such, we are not required to map the aesthetics for x and y. We simple provide just the data argument to ggpplot and then add a <code><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf()</a></code> layer. Inside of <code><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf()</a></code> we can provide any and all arguments that we may like such as color, size, shape, etc. as this will be passed to the underlying <code>geom_*</code>—in the case of points, it will be <code><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point()</a></code>.</p>
<div class="sourceCode" id="cb338"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">loc_sf</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="st">"."</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-7-1.png" width="100%"></div>
<p>This is great as we can already somewhat see the shape of Boston and Suffolk County. Since we have these Airbnb points located in space, we know we are able to associate them with their respective Census tracts.To do so we need another spatial data set which contains the shapes of each tract. In the next section we will read a dataset containing the shapes of each tract in Suffolk county. Following we will perform a spatial join to associate the points with the tracts.</p>
</div>
<div id="connecting-points-to-polygons" class="section level2" number="26.5">
<h2>
<span class="header-section-number">26.5</span> Connecting points to polygons<a class="anchor" aria-label="anchor" href="#connecting-points-to-polygons"><i class="fas fa-link"></i></a>
</h2>
<p>Now that we have the point locations of each Airbnb listing we need to identify which tracts they belong to. In the <code>data</code> folder there is a file called <code>suffolk_acs.geojson</code>. This is a common spatial data format which is based on <code>json</code>. The difference is that <code>geojson</code> contains a lot of fields specific to spatial data.</p>
<p>Reading in data of this format is just as easy as in reading in a csv file. Using <code><a href="https://rdrr.io/pkg/sf/man/st_read.html">sf::read_sf()</a></code> we can pass the path of the geojson file and be returned an sf object.</p>
<div class="sourceCode" id="cb339"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">acs_tracts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf</a></span><span class="op">(</span><span class="st">"data/suffolk_acs.geojson"</span><span class="op">)</span>

<span class="va">acs_tracts</span></code></pre></div>
<pre><code>## Simple feature collection with 203 features and 1 field
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -71.19125 ymin: 42.22793 xmax: -70.9201 ymax: 42.45012
## CRS:            4326
## # A tibble: 203 x 2
##    fips                                                                 geometry
##    &lt;chr&gt;                                                      &lt;MULTIPOLYGON [°]&gt;
##  1 250250921… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29301, -7…
##  2 250251006… (((-71.05147 42.28931, -71.05136 42.28933, -71.05032 42.28961, -7…
##  3 250250101… (((-71.11093 42.35047, -71.11093 42.3505, -71.11092 42.35054, -71…
##  4 250250704… (((-71.06944 42.346, -71.0691 42.34661, -71.06884 42.3471, -71.06…
##  5 250251401… (((-71.13397 42.25431, -71.13353 42.25476, -71.13274 42.25561, -7…
##  6 250259812… (((-71.04707 42.3397, -71.04628 42.34037, -71.0449 42.34153, -71.…
##  7 250250511… (((-71.01324 42.38301, -71.01231 42.38371, -71.01162 42.3842, -71…
##  8 250259816… (((-71.00113 42.3871, -71.001 42.38722, -71.00074 42.3875, -71.00…
##  9 250250909… (((-71.05079 42.32083, -71.0506 42.32076, -71.05047 42.32079, -71…
## 10 250251103… (((-71.11952 42.28648, -71.11949 42.2878, -71.11949 42.28792, -71…
## # … with 193 more rows</code></pre>
<p>The first things you’ll notice here is that it looks similar to our <code>loc_sf</code> object and, more importantly, that the CRS was picked up for us! If we briefly look under the hood of our file, we can see that in the third line the CRS is stated. You don’t need to understand what is happening here. Just know that sometimes spatial data sets already have this information for you.</p>
<pre><code>## {
## "type": "FeatureCollection",
## "name": "suffolk_acs",
## "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },</code></pre>
<p>Let’s see what this file looks like!</p>
<div class="sourceCode" id="cb342"><pre class="downlit sourceCode r">
<code class="sourceCode R">  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">acs_tracts</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-10-1.png" width="100%"></div>
<p>Wonderful! There are two stylist adjustments I’d make here so that visualizing is a little easier. The first is to change the line width to something thinner, and adjust the transparency of tracts so that they are a little lighter. This makes the map a bit easier to read all in all.</p>
<div class="sourceCode" id="cb343"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">acs_tracts</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">0.25</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-11-1.png" width="100%"></div>
<p>Now, here is where understanding the grammar of graphics comes in handy. We now have two different data sets that would be good to visualize together. Recall that when we specify the data in the top level <code><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot()</a></code> call that sets the default for every single layer. If we do that with multiple objects that may cause some conflicts. We do know, however, that we can set the data per layer. So, taking these two points together, we can plot both <code>loc_sf</code> <em>and</em> <code>acs_tracts</code> on the same graph if we set the data argument in each respective <code><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf()</a></code> layer.</p>
<div class="sourceCode" id="cb344"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">acs_tracts</span>, lwd <span class="op">=</span> <span class="fl">0.25</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">loc_sf</span>, shape <span class="op">=</span> <span class="st">"."</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-12-1.png" width="100%"></div>
<p>With the above plot we can get a sense of the density of Airbnb listings in Boston. There seems to be greater density near Back Bay and Beacon Hill. It would be great to be able to know how many listings there are for each tract and the average listing price. To do this, we need to perform two joins. The first one is spatial—joining point to polygon based on which tract each point intersects. The second is to join the listings information on to the spatially joined data set. In doing this we will have utilized data from three different sources!</p>
<div id="spatial-joins" class="section level3" number="26.5.1">
<h3>
<span class="header-section-number">26.5.1</span> Spatial Joins<a class="anchor" aria-label="anchor" href="#spatial-joins"><i class="fas fa-link"></i></a>
</h3>
<p>Like a regular join, the intent behind a spatial join is to add the attributes of one data source to another. The utility of a spatial join comes when there is no shared attribute <em>other than</em> space. More often than not when we want to perform a spatial join we are looking for what is called the <strong>intersection</strong>. That is essentially where two spatial features touch in some manner. The other type of spatial join that we will find useful is the nearest neighbor where we take the attributes to the next closest object.</p>
<p>To perform a spatial join we use the function <code><a href="https://rdrr.io/pkg/sf/man/st_join.html">sf::st_join()</a></code> which has three main arguments: <code>x</code>, <code>y</code>, and <code>join</code>. The default join type is <code>st_intersects</code> which will join attributes (columns) from <code>y</code> where <code>x</code> <strong>intersects</strong> (meaning touches or is within). The ordering of our <code>x</code> and <code>y</code> is very important as this will be the difference between a left or a right join. This ordering also determines what type of geometry we will be returned. Whatever type of geometry is in the <code>x</code> position is what will be returned.</p>
<p>Let’s try using <code><a href="https://rdrr.io/pkg/sf/man/st_join.html">st_join()</a></code> to join the tract level information to our point data.</p>
<div class="sourceCode" id="cb345"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">points_join</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_join.html">st_join</a></span><span class="op">(</span><span class="va">loc_sf</span>, <span class="va">acs_tracts</span><span class="op">)</span> </code></pre></div>
<pre><code>## although coordinates are longitude/latitude, st_intersects assumes that they are planar
## although coordinates are longitude/latitude, st_intersects assumes that they are planar</code></pre>
<div class="sourceCode" id="cb347"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">points_join</span></code></pre></div>
<pre><code>## Simple feature collection with 3799 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -71.1728 ymin: 42.23576 xmax: -70.99595 ymax: 42.39549
## CRS:            EPSG:4326
## # A tibble: 3,799 x 3
##       id             geometry fips       
##  * &lt;dbl&gt;          &lt;POINT [°]&gt; &lt;chr&gt;      
##  1  3781 (-71.02991 42.36413) 25025051200
##  2  5506 (-71.09559 42.32981) 25025081400
##  3  6695 (-71.09351 42.32994) 25025081400
##  4  8789 (-71.06265 42.35919) 25025030300
##  5 10730  (-71.06185 42.3584) 25025030300
##  6 10813 (-71.08904 42.34961) 25025010104
##  7 10986 (-71.05075 42.36352) 25025030300
##  8 16384  (-71.07132 42.3581) 25025020101
##  9 18711 (-71.06096 42.32212) 25025090700
## 10 22195  (-71.0793 42.34558) 25025010600
## # … with 3,789 more rows</code></pre>
<p>This is great! We now have the <code>fips</code> (census tract code) associated with each listing <code>id</code>. But what happens when we plot the data?</p>
<div class="sourceCode" id="cb349"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">points_join</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>shape <span class="op">=</span> <span class="st">"."</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-14-1.png" width="100%"></div>
<p>It is the same as before. What we would like to do at this moment is to plot the tracts and color by the number of listings contained in them. This means that we need to change up the order of our join.</p>
<div class="sourceCode" id="cb350"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">polygon_join</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_join.html">st_join</a></span><span class="op">(</span><span class="va">acs_tracts</span>, <span class="va">loc_sf</span><span class="op">)</span>
<span class="va">polygon_join</span></code></pre></div>
<pre><code>## Simple feature collection with 3814 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -71.19125 ymin: 42.22793 xmax: -70.9201 ymax: 42.45012
## CRS:            4326
## # A tibble: 3,814 x 3
##    fips                                                         geometry      id
##  * &lt;chr&gt;                                              &lt;MULTIPOLYGON [°]&gt;   &lt;dbl&gt;
##  1 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  3.63e6
##  2 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  7.22e6
##  3 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  7.29e6
##  4 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  3.36e7
##  5 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  3.63e7
##  6 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  3.89e7
##  7 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  4.02e7
##  8 25025092… (((-71.06249 42.29221, -71.06234 42.29273, -71.06226 42.29…  4.18e7
##  9 25025100… (((-71.05147 42.28931, -71.05136 42.28933, -71.05032 42.28…  2.64e7
## 10 25025100… (((-71.05147 42.28931, -71.05136 42.28933, -71.05032 42.28…  3.77e7
## # … with 3,804 more rows</code></pre>
<p>Notice that there are 3,814 rows! That is well over the original 193 tracts. If we tried plotting this right away we may overwork R. What we need to do is <em>count</em> the number of observations per fips code first.</p>
<div class="sourceCode" id="cb352"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tract_listings</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/count.html">count</a></span><span class="op">(</span><span class="va">polygon_join</span>, <span class="va">fips</span><span class="op">)</span>

<span class="va">tract_listings</span></code></pre></div>
<pre><code>## Simple feature collection with 203 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -71.19125 ymin: 42.22793 xmax: -70.9201 ymax: 42.45012
## CRS:            4326
## # A tibble: 203 x 3
##    fips           n                                                     geometry
##  * &lt;chr&gt;      &lt;int&gt;                                           &lt;MULTIPOLYGON [°]&gt;
##  1 250250001…    53 (((-71.1609 42.35863, -71.16049 42.35881, -71.16021 42.3589…
##  2 250250002…    18 (((-71.16782 42.35328, -71.16775 42.35351, -71.16764 42.353…
##  3 250250002…     4 (((-71.16057 42.35267, -71.16018 42.35269, -71.16005 42.352…
##  4 250250003…    19 (((-71.1748 42.35051, -71.17475 42.35066, -71.17471 42.3508…
##  5 250250003…    19 (((-71.17458 42.35024, -71.17287 42.35005, -71.17283 42.350…
##  6 250250004…    16 (((-71.15473 42.34121, -71.15455 42.34156, -71.15436 42.341…
##  7 250250004…    23 (((-71.16613 42.34043, -71.16612 42.34059, -71.16611 42.340…
##  8 250250005…    18 (((-71.16922 42.33807, -71.16909 42.33825, -71.16894 42.338…
##  9 250250005…    16 (((-71.15336 42.33819, -71.15308 42.33833, -71.15296 42.338…
## 10 250250005…     9 (((-71.1501 42.33719, -71.14984 42.33767, -71.14966 42.3379…
## # … with 193 more rows</code></pre>
<p>After counting we now have our original 203 rows. This is the spatial equivalent of summarizing our data where all of the geometries of the aggregated rows (<code>fips</code>) are <strong>dissolved</strong>. Dissolving combines all of the geometries of by a shared attribute—it is <code>fips</code> in our case—into a single geometry. Since each <code>fips</code> has the same geometry,the resultant geometries are unaffected. But be aware of the behavior when grouping and summarizing sf objects!</p>
<p>Let’s try plotting these counts now.</p>
<div class="sourceCode" id="cb354"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">tract_listings</span>, <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggsf.html">geom_sf</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="10-spatial-analysis_files/figure-html/unnamed-chunk-17-1.png" width="100%"></div>
<div id="resources" class="section level4" number="26.5.1.1">
<h4>
<span class="header-section-number">26.5.1.1</span> Resources<a class="anchor" aria-label="anchor" href="#resources"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li><a href="http://wiki.gis.com/wiki/index.php/Dissolve" class="uri">http://wiki.gis.com/wiki/index.php/Dissolve</a></li>
<li>For a full list of spatial joins by data type I recommend visiting <a href="https://desktop.arcgis.com/en/arcmap/latest/manage-data/tables/spatial-joins-by-feature-type.htm" class="uri">https://desktop.arcgis.com/en/arcmap/latest/manage-data/tables/spatial-joins-by-feature-type.htm</a>.</li>
<li><a href="https://geocompr.robinlovelace.net/" class="uri">https://geocompr.robinlovelace.net/</a></li>
<li><a href="https://rud.is/books/30-day-map-challenge/points-01.html" class="uri">https://rud.is/books/30-day-map-challenge/points-01.html</a></li>
</ul>
</div>
</div>
</div>
</div>




















































































  <div class="chapter-nav">
<div class="prev"><a href="statistics.html"><span class="header-section-number">25</span> Statistics</a></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#spatial-analysis"><span class="header-section-number">26</span> Spatial Analysis</a></li>
<li><a class="nav-link" href="#types-of-spatial-data"><span class="header-section-number">26.1</span> Types of spatial data</a></li>
<li><a class="nav-link" href="#working-with-spatial-data"><span class="header-section-number">26.2</span> Working with spatial data</a></li>
<li><a class="nav-link" href="#creating-simple-features-from-a-tibble"><span class="header-section-number">26.3</span> Creating simple features from a tibble</a></li>
<li><a class="nav-link" href="#plotting-sf-objects-with-ggplot"><span class="header-section-number">26.4</span> Plotting sf objects with ggplot</a></li>
<li>
<a class="nav-link" href="#connecting-points-to-polygons"><span class="header-section-number">26.5</span> Connecting points to polygons</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#spatial-joins"><span class="header-section-number">26.5.1</span> Spatial Joins</a></li></ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Urban Informatics Toolkit</strong>" was written by Josiah Parry. It was last built on 2021-01-07.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
