<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 25 Statistics | Urban Informatics Toolkit</title>
<meta name="author" content="Josiah Parry">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.5.3/header-attrs.js"></script><script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.3.9000/tabs.js"></script><script src="libs/bs3compat-0.2.3.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Urban Informatics Toolkit</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Welcome</a></li>
<li class="book-part">Foundations of Urban Informatics</li>
<li><a class="" href="the-utility-and-danger-of-big-data.html"><span class="header-section-number">2</span> The Utility and Danger of Big Data</a></li>
<li><a class="" href="data-in-the-municipal-context.html"><span class="header-section-number">3</span> Data in the municipal context</a></li>
<li><a class="" href="approaches-to-and-schools-of-urban-informatics.html"><span class="header-section-number">4</span> Approaches to and Schools of Urban Informatics</a></li>
<li><a class="" href="ecometrics.html"><span class="header-section-number">5</span> Ecometrics</a></li>
<li class="book-part">Toolkit Foundations</li>
<li><a class="" href="the-basics.html"><span class="header-section-number">6</span> The basics</a></li>
<li><a class="" href="r-as-a-calculator.html"><span class="header-section-number">7</span> R as a calculator</a></li>
<li><a class="" href="reading-data.html"><span class="header-section-number">8</span> Reading data</a></li>
<li><a class="" href="exploratory-visual-analysis.html"><span class="header-section-number">9</span> Exploratory Visual Analysis</a></li>
<li><a class="" href="general-data-manipulation.html"><span class="header-section-number">10</span> General data manipulation</a></li>
<li><a class="" href="thats-too-much-data.html"><span class="header-section-number">11</span> That’s too much data</a></li>
<li><a class="" href="the-pipe.html"><span class="header-section-number">12</span> The pipe %&gt;%</a></li>
<li><a class="" href="creating-new-measures.html"><span class="header-section-number">13</span> Creating new measures</a></li>
<li><a class="" href="data-structures.html"><span class="header-section-number">14</span> Data Structures</a></li>
<li><a class="" href="summary-statistics.html"><span class="header-section-number">15</span> Summary statistics</a></li>
<li><a class="" href="summarizing-the-tidy-way.html"><span class="header-section-number">16</span> Summarizing the tidy way</a></li>
<li><a class="" href="toolkit-review.html"><span class="header-section-number">17</span> Toolkit review</a></li>
<li class="book-part">Vizualization Strategies</li>
<li><a class="" href="layered-i.html"><span class="header-section-number">18</span> Grammar of layered graphics I</a></li>
<li><a class="" href="visualizing-trends-and-relationships.html"><span class="header-section-number">19</span> Visualizing Trends and Relationships</a></li>
<li><a class="" href="grammer-of-layered-graphics-ii.html"><span class="header-section-number">20</span> Grammer of layered graphics II</a></li>
<li><a class="" href="visualizing-beyond-2-dimensions.html"><span class="header-section-number">21</span> Visualizing beyond 2-dimensions</a></li>
<li><a class="" href="visualizing-through-time.html"><span class="header-section-number">22</span> Visualizing through time</a></li>
<li><a class="" href="visualization-review.html"><span class="header-section-number">23</span> Visualization Review</a></li>
<li class="book-part">Expanding the Toolkit</li>
<li><a class="" href="multiple-data-sets.html"><span class="header-section-number">24</span> Multiple data sets</a></li>
<li><a class="active" href="statistics.html"><span class="header-section-number">25</span> Statistics</a></li>
<li><a class="" href="spatial-analysis.html"><span class="header-section-number">26</span> Spatial Analysis</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="statistics" class="section level1" number="25">
<h1>
<span class="header-section-number">25</span> Statistics<a class="anchor" aria-label="anchor" href="#statistics"><i class="fas fa-link"></i></a>
</h1>
<p>In the course of your analyses you will both want to and need to conduct statistical tests. It is important that you are equipped to perform these tests in R as well. Teaching you statistical concepts is outside of the scope of this book. For an introduction to statistical concepts using R, I recommend reading David Dalpiaz’s free and open <a href="https://daviddalpiaz.github.io/r4sl/"><em>R for Statistical Learning</em></a><a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;em&gt;R for Statistical Learning&lt;/em&gt;. &lt;a href="https://daviddalpiaz.github.io/r4sl/" class="uri"&gt;https://daviddalpiaz.github.io/r4sl/&lt;/a&gt;.&lt;/p&gt;'><sup>74</sup></a>. In this section we will review <em>how</em> to implement statistical tests and extract useful information from them as well. We will cover t-tests, ANOVA, and linear regression.</p>
<p>To explore these statistics we will use data from Inside Airbnb. Of interest is the relationship between price and superhosts, price and room type, and finally how both superhosts and room type contribute to price.</p>
<div id="the-data-1" class="section level2" number="25.1">
<h2>
<span class="header-section-number">25.1</span> The data<a class="anchor" aria-label="anchor" href="#the-data-1"><i class="fas fa-link"></i></a>
</h2>
<p>We will use data from both the <code>hosts</code> and <code>listings</code> datasets. The former contains superhost data while the later has both the price and room type information. First we will read in both of these datasets.</p>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>

<span class="va">listings</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/airbnb/listings.csv"</span><span class="op">)</span>
<span class="va">hosts</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/airbnb/hosts.csv"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/tibble/man/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">listings</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 3,799
## Columns: 7
## $ id               &lt;dbl&gt; 3781, 5506, 6695, 8789, 10730, 10813, 10986, 16384, …
## $ neighborhood     &lt;chr&gt; "East Boston", "Roxbury", "Roxbury", "Downtown", "Do…
## $ room_type        &lt;chr&gt; "Entire home/apt", "Entire home/apt", "Entire home/a…
## $ price            &lt;dbl&gt; 125, 145, 169, 99, 150, 179, 125, 50, 154, 115, 148,…
## $ minimum_nights   &lt;dbl&gt; 28, 3, 3, 91, 91, 91, 91, 91, 29, 1, 2, 2, 2, 6, 3, …
## $ availability_365 &lt;dbl&gt; 68, 322, 274, 247, 29, 0, 364, 365, 304, 285, 62, 24…
## $ host_id          &lt;dbl&gt; 4804, 8229, 8229, 26988, 26988, 38997, 38997, 23078,…</code></pre>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tibble/man/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">hosts</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 1,335
## Columns: 9
## $ id              &lt;dbl&gt; 4804, 8229, 26988, 38997, 23078, 71783, 85130, 85770,…
## $ name            &lt;chr&gt; "Frank", "Terry", "Anne", "Michelle", "Eric", "Lance"…
## $ since_year      &lt;dbl&gt; 2008, 2009, 2009, 2009, 2009, 2010, 2010, 2010, 2010,…
## $ since_month     &lt;chr&gt; "12", "02", "07", "09", "06", "01", "02", "02", "03",…
## $ since_day       &lt;chr&gt; "03", "19", "22", "16", "24", "19", "24", "26", "23",…
## $ response_rate   &lt;chr&gt; "100%", "100%", "100%", "92%", "50%", "98%", "66%", "…
## $ acceptance_rate &lt;chr&gt; "50%", "100%", "84%", "17%", "N/A", "98%", "97%", "10…
## $ superhost       &lt;dbl&gt; 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,…
## $ n_listings      &lt;dbl&gt; 5, 2, 9, 13, 3, 40, 7, 4, 1, 2, 1, 1, 5, 1, 1, 1, 1, …</code></pre>
<p>In order to join these two tibbles together we need to figure out what the common identifiers are. In <code>listings</code> we can infer that the <strong>primary key</strong> is <code>id</code> while the <strong>foreign key</strong> is <code>host_id</code>. While the <code>hosts</code> tibble only has one <code>id</code> column. Clearly the join needs to be between <code>host_id</code> and <code>id</code> from <code>listings</code> and <code>hosts</code> respectively. We will perform a left join then select the columns <code>price</code>, <code>room_type</code> and <code>superhost</code> and assign that to the object <code>airbnb</code>.</p>
<div class="sourceCode" id="cb299"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">airbnb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">listings</span>, <span class="va">hosts</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"host_id"</span> <span class="op">=</span> <span class="st">"id"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/select.html">select</a></span><span class="op">(</span><span class="va">price</span>, <span class="va">room_type</span>, <span class="va">superhost</span><span class="op">)</span> 

<span class="fu"><a href="https://rdrr.io/pkg/tibble/man/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">airbnb</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 3,799
## Columns: 3
## $ price     &lt;dbl&gt; 125, 145, 169, 99, 150, 179, 125, 50, 154, 115, 148, 275, 2…
## $ room_type &lt;chr&gt; "Entire home/apt", "Entire home/apt", "Entire home/apt", "E…
## $ superhost &lt;dbl&gt; 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,…</code></pre>
<p>Before we can engage in any statistical testing we should do our due diligence and first visualize the relationship before we test it. Because we are comparing a group to a continuous variable a boxplot will suffice.</p>
<div class="sourceCode" id="cb301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">airbnb</span>, <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span><span class="va">price</span>, <span class="va">superhost</span>, group <span class="op">=</span> <span class="va">superhost</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-statistics_files/figure-html/unnamed-chunk-4-1.png" width="100%"></div>
<blockquote>
<p>Note that we are setting the group to <code>superhost</code> this is because it is dummy coded as a numeric value. ggplot is attempting to consider it numeric rather than categorical.</p>
</blockquote>
<p>Clearly there are some noticeable outliers above the $2,500 mark. Let’s filter out these values before we get on to our testing and while we’re at it, let’s convert <code>superhost</code> to a factor with <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code>. Save the the filtered results to <code>bnb_filt</code>. Recreate the above visualization with the new object.</p>
<div class="sourceCode" id="cb302"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bnb_filt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/filter.html">filter</a></span><span class="op">(</span><span class="va">airbnb</span>, <span class="va">price</span> <span class="op">&lt;</span> <span class="fl">2500</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>superhost <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">superhost</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">bnb_filt</span>, <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span><span class="va">price</span>, <span class="va">superhost</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-statistics_files/figure-html/unnamed-chunk-5-1.png" width="100%"></div>
<p>The first thing you may notices is that we no longer had to specify the <code>group</code> aesthetic because we converted <code>superhost</code> to a non-numeric format. From the above visualization it looks like that being a superhost does not necessarily increase the price of a listing. We can now test these means by using <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>. There are a number of ways in which we can use this function but the most generalizable way is to use what is called the <strong>formula</strong> interface.</p>
</div>
<div id="the-formula-interface" class="section level2" number="25.2">
<h2>
<span class="header-section-number">25.2</span> The formula interface<a class="anchor" aria-label="anchor" href="#the-formula-interface"><i class="fas fa-link"></i></a>
</h2>
<p>The formula interface is a way of defining <em>statistical</em> formulae. Or maybe a bit more clearly it let’s us tell R which columns to use when fitting a model<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;em&gt;R for Dummies&lt;/em&gt;. &lt;a href="https://www.dummies.com/programming/r/how-to-use-the-formula-interface-in-r/" class="uri"&gt;https://www.dummies.com/programming/r/how-to-use-the-formula-interface-in-r/&lt;/a&gt;.&lt;/p&gt;'><sup>75</sup></a>. The general format it takes is <code>y ~ x</code> which reads <em>y as a function of x</em>. In the case of a t-test the <code>y</code> is the variable that we will be testing the means of and the <code>x</code> is what group to compare. If our data are already in a tidy format—like our Airbnb data—this will be rather easy to adhere to.</p>
</div>
<div id="t-tests" class="section level2" number="25.3">
<h2>
<span class="header-section-number">25.3</span> T-tests<a class="anchor" aria-label="anchor" href="#t-tests"><i class="fas fa-link"></i></a>
</h2>
<p>To perform a t-test we will use the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function with the arguments <code>formula</code> and <code>data</code>. An example call looks like <code><a href="https://rdrr.io/r/stats/t.test.html">t.test(y ~ x, data = df)</a></code>. In our case our <code>y</code> is <code>price</code> because it is our variable of interest or our dependent variable. Since we are curious how <code>price</code> changes by <code>superhost</code> status, we will put <code>superhost</code> in the <code>x</code> spot.</p>
<p>Conduct a t-test and store the results in <code>price_t</code>. Print it out afterwards.</p>
<div class="sourceCode" id="cb303"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">price_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">superhost</span>, data <span class="op">=</span> <span class="va">bnb_filt</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  price by superhost
## t = 2.3261, df = 2029.4, p-value = 0.02011
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   1.949967 22.904491
## sample estimates:
## mean in group 0 mean in group 1 
##        175.1989        162.7717</code></pre>
<p>The above is a somewhat cluttered buch of numbers and words. But in there we can see our t-value (<code>t = 2.3261</code>), degrees of freedom (<code>df = 2029.4</code>), and our p-value (<code>p-value = 0.02011</code>). From this test we can tell that with an alpha level of 0.05 we can reject the null hypothesis.</p>
<div id="tidying-up-after-our-models" class="section level3" number="25.3.1">
<h3>
<span class="header-section-number">25.3.1</span> Tidying up after our models<a class="anchor" aria-label="anchor" href="#tidying-up-after-our-models"><i class="fas fa-link"></i></a>
</h3>
<p>While this is useful, we’re going to, at some point, want to extract these statistics in some usable format. Enter <a href="https://broom.tidyverse.org/"><code>broom</code></a>. From the documentation:</p>
<blockquote>
<p>"<code>broom</code> summarizes key information about models in tidy tibble()s. broom provides three verbs to make it convenient to interact with model objects.</p>
<ul>
<li>tidy() summarizes information about model components</li>
<li>glance() reports information about the entire model</li>
<li>augment() adds informations about observations to a dataset<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;{broom} &lt;a href="https://broom.tidyverse.org/" class="uri"&gt;https://broom.tidyverse.org/&lt;/a&gt;.&lt;/p&gt;'><sup>76</sup></a>
</li>
</ul>
</blockquote>
<p>Make sure that broom is installed with <code><a href="https://rdrr.io/r/utils/install.packages.html">install.packages("broom")</a></code>. Once that is installed use the function <code>tidy()</code> on the <code>price_t</code> object,</p>
<div class="sourceCode" id="cb305"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">price_t</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 10
##   estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
##      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1     12.4      175.      163.      2.33  0.0201     2029.     1.95      22.9
## # … with 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
<p>The result is a tibble that can be easily manipulated and worked with. But naturally we will want to explore beyond just two groups. And in that case we must perform an analysis of variance (ANOVA).</p>
</div>
</div>
<div id="anova" class="section level2" number="25.4">
<h2>
<span class="header-section-number">25.4</span> ANOVA<a class="anchor" aria-label="anchor" href="#anova"><i class="fas fa-link"></i></a>
</h2>
<p>The ANOVA test is used in the case when t-tests cannot. That is, they are used when we want to know if there is a difference in means between groups when there are two or more groups. To perform an ANOVA we use the <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> function—an initialism for <strong>a</strong>analysis <strong>o</strong>f <strong>v</strong>ariance—with the same arguments that we used in <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>. The only difference here is that the <code>x</code> is a column that has more than two groups—<code>room_type</code>. We can fit the ANOVA model with <code>price</code> as our <code>y</code> and <code>room_type</code> as our <code>x</code>.</p>
<div class="sourceCode" id="cb307"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">price_aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">room_type</span>, data <span class="op">=</span> <span class="va">bnb_filt</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = price ~ room_type, data = bnb_filt)
## 
## Terms:
##                 room_type Residuals
## Sum of Squares   15152015  70853604
## Deg. of Freedom         3      3789
## 
## Residual standard error: 136.7473
## Estimated effects may be unbalanced</code></pre>
<p>When we print out the ANOVA model object we actually don’t see the results we were anticipating. To get thos we have to pass the model object to the function <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>.</p>
<div class="sourceCode" id="cb309"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">price_aov</span><span class="op">)</span></code></pre></div>
<pre><code>##               Df   Sum Sq Mean Sq F value Pr(&gt;F)    
## room_type      3 15152015 5050672   270.1 &lt;2e-16 ***
## Residuals   3789 70853604   18700                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Now here we find the results of our test: p &lt; 0.001. You may notice already that there is some inconsistency in which that ways that models are interacted with. That is why we use broom, to have one common way of working with model objects. If we’d like to access the model results in a consistent way we can again use <code><a href="https://rdrr.io/pkg/generics/man/tidy.html">broom::tidy()</a></code>.</p>
<div class="sourceCode" id="cb311"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">price_aov</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 6
##   term         df     sumsq   meansq statistic    p.value
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 room_type     3 15152015. 5050672.      270.  7.32e-159
## 2 Residuals  3789 70853604.   18700.       NA  NA</code></pre>
<p>Remember though that ANOVA tests if there is <em>any</em> variation between any two groups. The results of the test do not tell us <em>which</em> groups are different. And this is when we turn to Tukey’s Honestly Significant Difference (HSD). Tukey’s HSD creates a set of confidence intervals to compare each unique combination of our variables. To perform the test in R we pass the ANOVA model object to the function <code><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD()</a></code></p>
<div class="sourceCode" id="cb313"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">price_hsd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span><span class="va">price_aov</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = price ~ room_type, data = bnb_filt)
## 
## $room_type
##                                     diff        lwr         upr     p adj
## Hotel room-Entire home/apt    -74.062500 -130.09198  -18.033019 0.0038353
## Private room-Entire home/apt -132.658355 -144.68495 -120.631764 0.0000000
## Shared room-Entire home/apt  -123.687500 -211.84397  -35.531026 0.0017890
## Private room-Hotel room       -58.595855 -115.00228   -2.189435 0.0381673
## Shared room-Hotel room        -49.625000 -153.58946   54.339462 0.6097851
## Shared room-Private room        8.970855  -79.42567   97.367379 0.9937854</code></pre>
<p>The results of the above test show that there are rather significant difference between hotel rooms and entire homes or apartments, private rooms and entire homes, shared rooms and entire homes, as well as private room and hotel room. With the use of broom and ggplot we can begin to visualize these restuls.</p>
<div class="sourceCode" id="cb315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">price_hsd_tidy</span> <span class="op">&lt;-</span> <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">price_hsd</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   term      comparison                   estimate conf.low conf.high adj.p.value
##   &lt;chr&gt;     &lt;chr&gt;                           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 room_type Hotel room-Entire home/apt     -74.1    -130.     -18.0      3.84e-3
## 2 room_type Private room-Entire home/apt  -133.     -145.    -121.       1.38e-8
## 3 room_type Shared room-Entire home/apt   -124.     -212.     -35.5      1.79e-3
## 4 room_type Private room-Hotel room        -58.6    -115.      -2.19     3.82e-2
## 5 room_type Shared room-Hotel room         -49.6    -154.      54.3      6.10e-1
## 6 room_type Shared room-Private room         8.97    -79.4     97.4      9.94e-1</code></pre>
<p>With the tidied HSD object we can create a graph of point estimates and error bars.</p>
<blockquote>
<p>I personally like to call these Tie Fighter plots because they resemble the space ships from Star Wars.</p>
</blockquote>
<p>We can being by plotting the point estimates of each comparison.</p>
<div class="sourceCode" id="cb317"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">price_hsd_tidy</span>, <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">comparison</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-statistics_files/figure-html/unnamed-chunk-13-1.png" width="100%"></div>
<p>Next we can add a horizontal error bar (<code><a href="https://rdrr.io/pkg/ggplot2/man/geom_errorbarh.html">geom_errorbarh()</a></code>) layer to the plot. This layer requires some additional aesthetics that we will set in the layer itself. These are <code>xmin</code> and <code>xmax</code>. Respectively they are used to mark the minimum and maximum extents of the error bars. In the case of the HSD object, the bounds of th confidence intervals have been already calculated for us and can be found in the columns <code>conf.low</code> and <code>conf.high</code>. We can pass these to the <code>xmin</code> and <code>xmax</code> aesthetic arguments.</p>
<div class="sourceCode" id="cb318"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_errorbarh.html">geom_errorbarh</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">conf.low</span>, xmax <span class="op">=</span> <span class="va">conf.high</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-statistics_files/figure-html/unnamed-chunk-14-1.png" width="100%"></div>
</div>
<div id="linear-regression" class="section level2" number="25.5">
<h2>
<span class="header-section-number">25.5</span> Linear regression<a class="anchor" aria-label="anchor" href="#linear-regression"><i class="fas fa-link"></i></a>
</h2>
<p>When we want to move on to inference with linear models, we turn to the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function. This, like the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> and <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> functions requires both a formula and data. The difference is that the formulas that we will use are a bit more complex because we will often be using many variables. To predict y as some function of multiple inputs we have to declare all of those inputs in our formula which takes form of <code>y ~ x1 + x2 + ...</code>. So if we were to create a linear model that predicts price as a function of room type and whether or the host is a superhost, our formula will look like <code>price ~ room_type + superhost</code>.</p>
<div class="sourceCode" id="cb319"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">price_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">room_type</span> <span class="op">+</span> <span class="va">superhost</span>, data <span class="op">=</span> <span class="va">bnb_filt</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">price_lm</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ room_type + superhost, data = bnb_filt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -219.01  -64.01  -26.01   20.99 1780.99 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            219.0073     3.0450  71.925  &lt; 2e-16 ***
## room_typeHotel room    -74.3532    21.8938  -3.396 0.000691 ***
## room_typePrivate room -132.7222     4.7004 -28.237  &lt; 2e-16 ***
## room_typeShared room  -123.5526    34.3168  -3.600 0.000322 ***
## superhost1               0.7244     4.9720   0.146 0.884172    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 136.8 on 3788 degrees of freedom
## Multiple R-squared:  0.1762, Adjusted R-squared:  0.1753 
## F-statistic: 202.5 on 4 and 3788 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The output of this is very similar to that of the ANOVA model. Perhaps we can visualize it the same way?</p>
<div class="sourceCode" id="cb321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">price_lm</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##   term                  estimate std.error statistic   p.value
##   &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)            219.         3.04    71.9   0.       
## 2 room_typeHotel room    -74.4       21.9     -3.40  6.91e-  4
## 3 room_typePrivate room -133.         4.70   -28.2   2.34e-159
## 4 room_typeShared room  -124.        34.3     -3.60  3.22e-  4
## 5 superhost1               0.724      4.97     0.146 8.84e-  1</code></pre>
<p>Unfortunately when we tidy this up we don’t have the same columns. However we can ask for them explicitly by setting the argument <code>conf.int = TRUE</code>.</p>
<blockquote>
<p>You can find all possible arguments for <code>tidy()</code> in the exported object <code><a href="https://rdrr.io/pkg/broom/man/argument_glossary.html">broom::argument_glossary</a></code>.</p>
</blockquote>
<p>Using a similar structure as above, we can create a coefficient plot.</p>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">price_lm</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">term</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_errorbarh.html">geom_errorbarh</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">conf.low</span>, xmax <span class="op">=</span> <span class="va">conf.high</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="09-statistics_files/figure-html/unnamed-chunk-17-1.png" width="100%"></div>
<p>Unlike the t-test, a linear model provides much more information that will become useful such as goodness of fit measures, residuals, and predicted values. To extract these we can use the functions <code>glance()</code> and <code>augment()</code> from broom.</p>
<div class="sourceCode" id="cb324"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/glance.html">glance</a></span><span class="op">(</span><span class="va">price_lm</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##   r.squared adj.r.squared sigma statistic   p.value    df  logLik    AIC    BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1     0.176         0.175  137.      203. 1.29e-157     5 -24035. 48081. 48118.
## # … with 2 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb326"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/generics/man/augment.html">augment</a></span><span class="op">(</span><span class="va">price_lm</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 10
##   price room_type superhost .fitted .se.fit .resid    .hat .sigma .cooksd
##   &lt;dbl&gt; &lt;chr&gt;     &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1   125 Entire h… 1            220.    4.66  -94.7 0.00116   137. 1.12e-4
## 2   145 Entire h… 1            220.    4.66  -74.7 0.00116   137. 6.94e-5
## 3   169 Entire h… 1            220.    4.66  -50.7 0.00116   137. 3.20e-5
## 4    99 Entire h… 1            220.    4.66 -121.  0.00116   137. 1.81e-4
## 5   150 Entire h… 1            220.    4.66  -69.7 0.00116   137. 6.04e-5
## # … with 1 more variable: .std.resid &lt;dbl&gt;</code></pre>

</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="multiple-data-sets.html"><span class="header-section-number">24</span> Multiple data sets</a></div>
<div class="next"><a href="spatial-analysis.html"><span class="header-section-number">26</span> Spatial Analysis</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#statistics"><span class="header-section-number">25</span> Statistics</a></li>
<li><a class="nav-link" href="#the-data-1"><span class="header-section-number">25.1</span> The data</a></li>
<li><a class="nav-link" href="#the-formula-interface"><span class="header-section-number">25.2</span> The formula interface</a></li>
<li>
<a class="nav-link" href="#t-tests"><span class="header-section-number">25.3</span> T-tests</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#tidying-up-after-our-models"><span class="header-section-number">25.3.1</span> Tidying up after our models</a></li></ul>
</li>
<li><a class="nav-link" href="#anova"><span class="header-section-number">25.4</span> ANOVA</a></li>
<li><a class="nav-link" href="#linear-regression"><span class="header-section-number">25.5</span> Linear regression</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Urban Informatics Toolkit</strong>" was written by Josiah Parry. It was last built on 2021-01-05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
